operators = [
    '=', '>', '<', '>=', '<=', '!=', '<>', 'LIKE',
    'IN', 'NOT IN', 'BETWEEN', 'IS NULL', 'IS NOT NULL',
    'AND', 'OR', 'NOT', '+', '-', '*', '/', '%', '||'
]

brackets = ['(', ')']

function_names= [
    'COUNT', 'SUM', 'AVG', 'MIN', 'MAX', 'FIRST', 'LAST', 'MID', 'LEN', 'ROUND', 'NOW', 'FORMAT', 'DATE', 'DATEADD', 'DATEDIFF', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS', 'DATEADD', 'DATEPART', 'DATENAME', 'DATEFROMPARTS']


reservedWords = list(keywords.KEYWORDS_COMMON) +list(keywords.KEYWORDS_ORACLE)+list(keywords.KEYWORDS_PLPGSQL)+list(keywords.KEYWORDS_HQL)+list(keywords.KEYWORDS_MSACCESS)+ list(keywords.KEYWORDS) +['*']
